In [ ]:
from numpy import array
from numpy import mean
from numpy import cov
from numpy.linalg import eig


In [ ]:
# dataset

D = array([[4, 11], [8, 4], [13, 5], [7, 14]])
print(D)

[[ 4 11]
 [ 8  4]
 [13  5]
 [ 7 14]]


In [ ]:
print(D.T)

[[ 4  8 13  7]
 [11  4  5 14]]


In [ ]:
# calculating mean
M = mean(D.T,axis = 1)
print(M)

[8.  8.5]


In [ ]:
A = D - M
print(A)

[[-4.   2.5]
 [ 0.  -4.5]
 [ 5.  -3.5]
 [-1.   5.5]]


In [ ]:
# claculating covariance matrix
C = cov(A.T)

print(C)

[[ 14. -11.]
 [-11.  23.]]


In [ ]:
eig_values, eig_vectors = eig(C)

In [ ]:
# print eigen values

print(eig_values)

[ 6.61513568 30.38486432]


In [ ]:
# print eigen vectors

print(eig_vectors)

[[-0.83025082  0.55738997]
 [-0.55738997 -0.83025082]]


In [ ]:
pca = eig_vectors.T.dot(A.T)

In [ ]:
# print principle component

print(pca)

[[ 1.92752836  2.50825486 -2.20038921 -2.23539401]
 [-4.30518692  3.73612869  5.69282771 -5.12376947]]
